# Generated by Django 3.1.1 on 2020-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographygal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='comments',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
