# Generated by Django 3.1.1 on 2020-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographygal', '0002_auto_20200918_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='comments',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='comments',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
