# Generated by Django 3.1.1 on 2020-09-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographygal', '0003_auto_20200921_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='title',
        ),
    ]
