# Generated by Django 3.1.1 on 2020-09-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographygal', '0005_gallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='photographygal.gallery'),
        ),
    ]
